### ISSUE TITLE
Support inline YAML in aci_rest

### ISSUE THREAD

**Issue by dagwieers** [datacenter/aci-ansible#110]
So rather than ask for XML or JSON snippets, we could map inline YAML directly into playbooks to make playbooks  more natural for configuration.

This will make it easier for people to support missing functionality directly from the documentation.

```yaml
- aci_rest:
    << *aci_login
    path: /api/mo/uni/controller/nodeidentpol.xml
    content:
        fabricNodeIdentPol:
            children:
                fabricNodeIdentP:
                    attributes:
                        name: '{{ item.name }}'
                        nodeId: '{{ item.nodeid }}'
                        status: '{{ item.status }}'
                        serial: '{{ item.serial }}'
  with_items:
  - '{{ apic_leavesspines }}'
  delegate_to: localhost
```
And it would be quite easy to support right away.
