### ISSUE TITLE
Idempotency in APIC REST APIs

### ISSUE THREAD

**Issue by joelwking** [datacenter/aci-ansible#111]
The APIC northbound REST API implements Idempotency natively, meaning if you use the API to create a tenant, it will create it the first time, but subsequent API calls will not make changes to the APIC configuration if the tenant exists and all the values of the tenant are the same.
 
However, running it the first time gives you a return code of 200 and running it the second time also gives you a return code of 200.   So how do you know if anything was modified on the second request?
 
The APIC rest API has an option for POST requests in the form of “?rsp-subtree=modified”.  When specified, this indicates to the API you are requesting a response from the POST operation.  If the API must create the object (the Tenant, for example) the response will be XML with an attribute and value of status=”created”.  If the API must made changes to the existing object, the response will be status=”modified”. 
 
If nothing is changed, you don’t get any response back, other than the return code 200.
 
By enabling the request response option on the REST calls, and examining if the status attribute exists, you can return this info when existing an Ansible module and accurately specify the ‘changed’ flag, and being idempotent.

I implement this in https://github.com/joelwking/ansible-aci/blob/master/aci_install_config.py 
beginning at line 151 and then line 165.

Example:

The IPv6 network `fd00:a:255:64::1/64` does not exist prior to running this playbook.
```bash
administrator@russell:~/ansible/playbooks$ ./apic_idempotency.yml

PLAY [IPv6_v2] ****************************************************************************************************

TASK [Include credentials from an encrypted password.yml file] ****************************************************
ok: [aci-demo.sandbox.wwtatc.local]

TASK [Create L3 Configurations] ***********************************************************************************
changed: [aci-demo.sandbox.wwtatc.local] => (item={u'net': u'1', u'addr': u'fd00:a:255:64::1/64'})
ok: [aci-demo.sandbox.wwtatc.local] => (item={u'net': u'1', u'addr': u'fd00:a:255:64::1/64'})

TASK [Delete  L3 Configurations] **********************************************************************************
changed: [aci-demo.sandbox.wwtatc.local] => (item={u'net': u'1', u'addr': u'fd00:a:255:64::1/64'})
ok: [aci-demo.sandbox.wwtatc.local] => (item={u'net': u'1', u'addr': u'fd00:a:255:64::1/64'})

PLAY RECAP ********************************************************************************************************
aci-demo.sandbox.wwtatc.local : ok=3    changed=2    unreachable=0    failed=0
```
Note in the above output, I loop thru each task twice. The first time I create/delete the IPv6 network, and the changed flag is set to changed, the second time it is not.

```yaml
#!/usr/bin/ansible-playbook
#
#      Copyright (c) 2017 World Wide Technology, Inc.
#      All rights reserved.
#      author: @joelwking
#
---
- name: "IPv6_v2"
  hosts:  aci-demo.sandbox.wwtatc.local
  connection: local
  gather_facts: no

  vars:
    IPv6_addr:
        - {"net": "1", "addr": "fd00:a:255:64::1/64"}
        - {"net": "1", "addr": "fd00:a:255:64::1/64"}

  tasks:
    - name: Include credentials from an encrypted password.yml file
      include_vars: "./passwords.yml"
      tags: always

    - name: "Create L3 Configurations"
      aci_install_config:
        URI: /api/mo/uni.xml
        xml_file: "./files/__L3_Configurations{{item.net}}.xml"
        host: "{{inventory_hostname}}"
        username: "{{apic.username}}"
        password: "{{apic.password}}"
      tags: create
      with_items: "{{IPv6_addr}}"

    - name: "Delete  L3 Configurations"
      aci_install_config:
        URI: /api/mo/uni.xml
        xml_file: "./files/__L3_Configurations_del{{item.net}}.xml"
        host: "{{inventory_hostname}}"
        username: "{{apic.username}}"
        password: "{{apic.password}}"
      tags: delete
      with_items: "{{IPv6_addr}}"
```
Create the L3 network
```xml
$ cat __L3_Configurations1.xml
<fvSubnet ctrl=""
descr=""
dn="uni/tn-common/BD-Common/subnet-[fd00:a:255:64::1/64]"
ip="fd00:a:255:64::1/64"
name=""
nameAlias=""
preferred="no"
scope="public"
status=""
virtual="no">
<fvRsNdPfxPol tnNdPfxPolName="ACI-Demo-RA"/>
</fvSubnet>
```
Delete the L3 network
```xml
$ cat __L3_Configurations_del1.xml
<fvSubnet ctrl=""
descr=""
dn="uni/tn-common/BD-Common/subnet-[fd00:a:255:64::1/64]"
ip="fd00:a:255:64::1/64"
name=""
nameAlias=""
preferred="no"
scope="public"
status="deleted"
virtual="no">
<fvRsNdPfxPol tnNdPfxPolName="ACI-Demo-RA"/>
</fvSubnet>
```
Your mileage may vary.
