### ISSUE TITLE
aci_rest: Attributes are missing, tag 'attributes' must be specified first, before any other tag

### ISSUE THREAD

**Issue by dagwieers** [datacenter/aci-ansible#167]
When you use the YAML or JSON payload format, ACI requires an `attributes` entry even when there are no attributes needed. It will complain with:
```
Attributes are missing, tag 'attributes' must be specified first, before any other tag
```
You can add an empty attributes entry by doing `attributes: {}` like the example below:
```yaml
 - name: Create a switch profile
    aci_rest:
      <<: *aci_login
      path: /api/policymgr/mo/uni.json
      method: post
      content:
        infraInfra:
          attributes: {}
          children:
          - infraNodeP:
-cut-
```

We could make aci_rest add empty attributes-entries if they are missing.
