### ISSUE TITLE
aci_rest fails on HTTP 400 "already_exists"

### ISSUE THREAD

**Issue by brunocalogero** [datacenter/aci-ansible#179]
The following is a bug report for the  "aci_rest" module, 

When executing for example the following: 

```yaml

- name: Creating Interface Policy Group (add module)
  aci_rest:
    <<: *aci_login
    path: /api/node/mo/uni/infra/funcprof/accportgrp-L2-BPDUguard-IfPolGrp.json
    method: post
    content: |
      {
        "infraAccPortGrp": {
          "attributes": {
            "dn": "uni/infra/funcprof/accportgrp-L2-BPDUguard-IfPolGrp",
            "name": "L2-BPDUguard-IfPolGrp",
            "descr": "certification leaf policy group",
            "rn": "accportgrp-L2-BPDUguard-IfPolGrp",
            "status": "created"
          },
          "children": [{
            "infraRsAttEntP": {
              "attributes": {
                "tDn": "uni/infra/attentp-L2-BPDUforward-AEP",
                "status": "created,modified"
              },
              "children": []
            }
          }, {
            "infraRsHIfPol": {
              "attributes": {
                "tnFabricHIfPolName": "10G-IfPol",
                "status": "created,modified"
              },
              "children": []
            }
          }, {
            "infraRsCdpIfPol": {
              "attributes": {
                "tnCdpIfPolName": "cdpEnable-IfPol",
                "status": "created,modified"
              },
              "children": []
            }
          }, {
            "infraRsLldpIfPol": {
              "attributes": {
                "tnLldpIfPolName": "lldpDisable-IfPol",
                "status": "created,modified"
              },
              "children": []
            }
          }, {
            "infraRsStpIfPol": {
              "attributes": {
                "tnStpIfPolName": "bpduGuardEnable-IfPol",
                "status": "created,modified"
              },
              "children": []
            }
          }, {
            "infraRsL2IfPol": {
              "attributes": {
                "tnL2IfPolName": "Port-local-L2-Policy",
                "status": "created,modified"
              },
              "children": []
            }
          }]
        }
      }
  delegate_to: localhost

```

I obtain the following traceback: 

```json
The full traceback is:
  File "/var/folders/ht/bgw3x1bs6mbfp55kc53wfd3r0000gp/T/ansible_GGGb8j/ansible_module_aci_rest.py", line 236, in <module>
    from xmljson import cobra

fatal: [layer_2_features_certification -> localhost]: FAILED! => {
    "changed": false, 
    "error_code": "103", 
    "error_text": "Cannot create Leaf Access Port Policy Group (infraAccPortGrp); object uni/infra/funcprof/accportgrp-L2-BPDUguard-IfPolGrp already exists.", 
    "failed": true, 
    "imdata": [
        {
            "error": {
                "attributes": {
                    "code": "103", 
                    "text": "Cannot create Leaf Access Port Policy Group (infraAccPortGrp); object uni/infra/funcprof/accportgrp-L2-BPDUguard-IfPolGrp already exists."
                }
            }
        }
    ], 
    "invocation": {
        "module_args": {
            "content": "{\n  \"infraAccPortGrp\": {\n    \"attributes\": {\n      \"dn\": \"uni/infra/funcprof/accportgrp-L2-BPDUguard-IfPolGrp\",\n      \"name\": \"L2-BPDUguard-IfPolGrp\",\n      \"descr\": \"certification leaf policy group\",\n      \"rn\": \"accportgrp-L2-BPDUguard-IfPolGrp\",\n      \"status\": \"created\"\n    },\n    \"children\": [{\n      \"infraRsAttEntP\": {\n        \"attributes\": {\n          \"tDn\": \"uni/infra/attentp-L2-BPDUforward-AEP\",\n          \"status\": \"created,modified\"\n        },\n        \"children\": []\n      }\n    }, {\n      \"infraRsHIfPol\": {\n        \"attributes\": {\n          \"tnFabricHIfPolName\": \"10G-IfPol\",\n          \"status\": \"created,modified\"\n        },\n        \"children\": []\n      }\n    }, {\n      \"infraRsCdpIfPol\": {\n        \"attributes\": {\n          \"tnCdpIfPolName\": \"cdpEnable-IfPol\",\n          \"status\": \"created,modified\"\n        },\n        \"children\": []\n      }\n    }, {\n      \"infraRsLldpIfPol\": {\n        \"attributes\": {\n          \"tnLldpIfPolName\": \"lldpDisable-IfPol\",\n          \"status\": \"created,modified\"\n        },\n        \"children\": []\n      }\n    }, {\n      \"infraRsStpIfPol\": {\n        \"attributes\": {\n          \"tnStpIfPolName\": \"bpduGuardEnable-IfPol\",\n          \"status\": \"created,modified\"\n        },\n        \"children\": []\n      }\n    }, {\n      \"infraRsL2IfPol\": {\n        \"attributes\": {\n          \"tnL2IfPolName\": \"Port-local-L2-Policy\",\n          \"status\": \"created,modified\"\n        },\n        \"children\": []\n      }\n    }]\n  }\n}\n", 
            "hostname": "svlngen4-fab4-apic2.cisco.com", 
            "method": "post", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "path": "/api/node/mo/uni/infra/funcprof/accportgrp-L2-BPDUguard-IfPolGrp.json", 
            "protocol": "http", 
            "src": null, 
            "timeout": 30, 
            "use_proxy": true, 
            "use_ssl": false, 
            "username": "admin", 
            "validate_certs": false
        }
    }, 
    "msg": "Request failed: 103 Cannot create Leaf Access Port Policy Group (infraAccPortGrp); object uni/infra/funcprof/accportgrp-L2-BPDUguard-IfPolGrp already exists.", 
    "payload": "{\"infraAccPortGrp\": {\"attributes\": {\"dn\": \"uni/infra/funcprof/accportgrp-L2-BPDUguard-IfPolGrp\", \"status\": \"created\", \"rn\": \"accportgrp-L2-BPDUguard-IfPolGrp\", \"name\": \"L2-BPDUguard-IfPolGrp\", \"descr\": \"certification leaf policy group\"}, \"children\": [{\"infraRsAttEntP\": {\"attributes\": {\"status\": \"created,modified\", \"tDn\": \"uni/infra/attentp-L2-BPDUforward-AEP\"}, \"children\": []}}, {\"infraRsHIfPol\": {\"attributes\": {\"status\": \"created,modified\", \"tnFabricHIfPolName\": \"10G-IfPol\"}, \"children\": []}}, {\"infraRsCdpIfPol\": {\"attributes\": {\"status\": \"created,modified\", \"tnCdpIfPolName\": \"cdpEnable-IfPol\"}, \"children\": []}}, {\"infraRsLldpIfPol\": {\"attributes\": {\"status\": \"created,modified\", \"tnLldpIfPolName\": \"lldpDisable-IfPol\"}, \"children\": []}}, {\"infraRsStpIfPol\": {\"attributes\": {\"status\": \"created,modified\", \"tnStpIfPolName\": \"bpduGuardEnable-IfPol\"}, \"children\": []}}, {\"infraRsL2IfPol\": {\"attributes\": {\"status\": \"created,modified\", \"tnL2IfPolName\": \"Port-local-L2-Policy\"}, \"children\": []}}]}}", 
    "response": "HTTP Error 400: Bad Request", 
    "status": 400, 
    "totalCount": "1", 
    "url": "http://svlngen4-fab4-apic2.cisco.com/api/node/mo/uni/infra/funcprof/accportgrp-L2-BPDUguard-IfPolGrp.json?rsp-subtree=modified"
}
```

This will stop my playbook from continuing to run, ideally the module would handle this 400 error and ignore the fact that we are trying to overwrite through the POST.
