### ISSUE TITLE
Consistent naming for modules (incl. complex names)

### ISSUE THREAD

**Issue by dagwieers** [datacenter/aci-ansible#88]
So when looking at [the missing functionality](https://github.com/ansible/community/wiki/Network:-ACI#needed) that Ramses wants to use, a lot of new modules would need to be created. The problem is that the more functionality of ACI we are looking at, the more complex the naming is starting to become. So we have a really big issue here.

There are 3 options:
1. Use common names (e.g. from GUI) or as used in training and with customers for entities:
   - aci_vrf instead of aci_context
   - aci_bd instead of aci_bridge_domain
   Keep the long names, but maybe removing `_binding` from the name, and use aci_<long_name>_to_<other_long_name>
2. Create a better terminology for the existing modules (esp. the binding modules) that should be consistent
   - i.e., now we use **bridge_domain** in one place and elsewhere call it **bd**
   - More complex examples are listed [here](https://github.com/ansible/community/wiki/Network:-ACI#needed)
    - aci_accessport_selector_policy_group_binding
    - aci_leaf_interface_profile_accessport_selector_binding
3. ~Implement the low-level names and use these for the module names (but provide the details in the short_description/description).~
   - aci_aep --> aci_infra_attentp
   - aci_anp --> aci_fv_ap
   - aci_bd_l3out_binding --> aci_fv_rsbdtoout
   - aci_bridge_domain --> aci_fv_bd
   - aci_context --> aci_fv_ctx
   - aci_ contract --> aci_vz_brcp
   - aci_contract_subject --> aci_vz_subj
   - aci_epg_contract_binding --> aci_fv_rscons + aci_fv_rsprov

**Comment by dagwieers** [comment]
1. My preference would be the first, but making a terminology list:
    - bd (bridge_domain)
    - ap (application profile)
    - apg (accessport_group)
    - aps (accessport_selector)
    - lip (leaf_interface_profile)
    - pg (policy_group)
2. And we should stick to the above naming convention everywhere.
3. We should add the low-level name to the short-description *and* as a standard entry to the description.
    So for aci_ap it would be:
    ```yaml
    short_description: Manage top level application profile (AP) objects on Cisco ACI fabrics [fv:ap]
    description:
    - Manage top level application profile (AP) objects on Cisco ACI fabrics.
    - This maps directly into the internal C(fv:af), see U(https://developer.cisco.com/media/mim-ref/MO-fvAp.html)
    ```
