### ISSUE TITLE
Add internal names to descriptions

### ISSUE THREAD

**Issue by dagwieers** [datacenter/aci-ansible#89]
After looking at the object model and mapping Cobra-stuff to Ansible playbooks, I think what would really help Cisco customers is to add the low-level name to the short-description *and* as a standard entry to the description.

So for aci_ap (*not* aci_anp) it would be:
```yaml
    short_description: Manage top level application profile (AP) objects on Cisco ACI fabrics [fv:Ap]
    description:
    - Manage top level application profile (AP) objects on Cisco ACI fabrics.
    - More information from the internal APIC class C(fv:Ap) at U(https://developer.cisco.com/media/mim-ref/MO-fvAp.html)
```
